concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "eq10-stat-jeu-video-runner-1"
  url = "https://depot.dinf.usherbrooke.ca/"
  id = 297
  token = "P6RnXzbsZ1pLi4KRi9yc"
  token_obtained_at = 2023-01-27T04:34:06Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
    shm_size = 0

[[runners]]
  name = "eq10-stat-jeu-video-runner-1"
  url = "https://depot.dinf.usherbrooke.ca/"
  id = 298
  token = "yhCtnHhPnBikyv-3n-gQ"
  token_obtained_at = 2023-01-27T04:36:19Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/certs/client", "/cache"]
    shm_size = 0
